version: '3.2'

services:
  lb:
    build:
      context: ./lb
      dockerfile: Dockerfile
    networks:
      testnet:
        aliases:
          - google.com
          - www.google.com

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: guardian 
      KEYCLOAK_PASSWORD: mutabor 
      DB_VENDOR: h2 
      PROXY_ADDRESS_FORWARDING: "true"
    volumes:
      - ./kc/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
    networks: [ 'testnet' ]

  socks:
    image: serjs/go-socks5-proxy
    ports: [ '8910:1080' ]
    networks: [ 'testnet' ]

networks:
  testnet:
